<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoundSourcesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('sound_sources')->insert([
            // === 無料音源（基本3つ） ===
            [
                'id' => 1,
                'name' => 'ピアノ',
                'type' => 'piano',
                'category' => 'basic',
                'file_path' => null, // Web Audio APIで生成
                'is_free' => true,
                'price' => 0,
                'icon_path' => '🎹',
                'description' => '美しく響くピアノの音色。基本となる音源で、あらゆる楽曲に調和します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'ハープ',
                'type' => 'harp',
                'category' => 'basic',
                'file_path' => null,
                'is_free' => true,
                'price' => 0,
                'icon_path' => '🎵',
                'description' => '天使の楽器とも呼ばれるハープ。優雅で繊細な音色が特徴的です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'シンセパッド',
                'type' => 'synth_pad',
                'category' => 'basic',
                'file_path' => null,
                'is_free' => true,
                'price' => 0,
                'icon_path' => '🎛️',
                'description' => '暖かく包み込むようなシンセサイザーの音色。アンビエント音楽に最適です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === QRコード取得音源（和楽器パック） ===
            [
                'id' => 4,
                'name' => '琴（こと）',
                'type' => 'japanese_koto',
                'category' => 'japanese',
                'file_path' => null,
                'is_free' => false,
                'price' => 500,
                'icon_path' => '🎌',
                'description' => '日本の伝統楽器、琴の美しい音色。雅な響きが公園に和の趣を添えます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => '尺八（しゃくはち）',
                'type' => 'japanese_shakuhachi',
                'category' => 'japanese',
                'file_path' => null,
                'is_free' => false,
                'price' => 500,
                'icon_path' => '🎋',
                'description' => '竹製の縦笛、尺八の深みのある音色。風の音と調和する神秘的な響きです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => '太鼓（たいこ）',
                'type' => 'japanese_taiko',
                'category' => 'japanese',
                'file_path' => null,
                'is_free' => false,
                'price' => 500,
                'icon_path' => '🥁',
                'description' => '力強い和太鼓の響き。リズムセクションとして楽曲に躍動感を与えます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => '鈴（すず）',
                'type' => 'japanese_suzu',
                'category' => 'japanese',
                'file_path' => null,
                'is_free' => false,
                'price' => 500,
                'icon_path' => '🔔',
                'description' => '清らかな鈴の音色。神社の境内を思わせる神聖な響きが特徴的です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === QRコード取得音源（80'sシンセパック） ===
            [
                'id' => 8,
                'name' => 'DX7エレピ',
                'type' => 'synth80s_dx7',
                'category' => '80s_synth',
                'file_path' => null,
                'is_free' => false,
                'price' => 800,
                'icon_path' => '⚡',
                'description' => '80年代を代表するFM音源、DX7のエレクトリックピアノサウンド。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Jupiter-8',
                'type' => 'synth80s_jupiter',
                'category' => '80s_synth',
                'file_path' => null,
                'is_free' => false,
                'price' => 800,
                'icon_path' => '🌟',
                'description' => 'Roland Jupiter-8の豊かなアナログシンセサウンド。温かみのある音色が魅力。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Juno-106',
                'type' => 'synth80s_juno',
                'category' => '80s_synth',
                'file_path' => null,
                'is_free' => false,
                'price' => 800,
                'icon_path' => '🎚️',
                'description' => 'Roland Juno-106の特徴的なコーラス効果が美しいシンセサウンド。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Moog Bass',
                'type' => 'synth80s_moog',
                'category' => '80s_synth',
                'file_path' => null,
                'is_free' => false,
                'price' => 800,
                'icon_path' => '🎸',
                'description' => 'Moogシンセサイザーの重厚なベースサウンド。低音の迫力が印象的。',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === QRコード取得音源（自然音パック） ===
            [
                'id' => 12,
                'name' => '鳥のさえずり',
                'type' => 'nature_birds',
                'category' => 'nature',
                'file_path' => null,
                'is_free' => false,
                'price' => 300,
                'icon_path' => '🐦',
                'description' => '早朝の公園に響く美しい鳥のさえずり。自然の音楽そのものです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => '水の音',
                'type' => 'nature_water',
                'category' => 'nature',
                'file_path' => null,
                'is_free' => false,
                'price' => 300,
                'icon_path' => '💧',
                'description' => '清らかな小川や噴水の水音。心を落ち着かせる癒しの音色。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => '風の音',
                'type' => 'nature_wind',
                'category' => 'nature',
                'file_path' => null,
                'is_free' => false,
                'price' => 300,
                'icon_path' => '🍃',
                'description' => '木々を揺らす優しい風の音。自然の呼吸を感じられる音色。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => '虫の声',
                'type' => 'nature_insects',
                'category' => 'nature',
                'file_path' => null,
                'is_free' => false,
                'price' => 300,
                'icon_path' => '🦗',
                'description' => '夏の夜に響く虫の合唱。日本の夏の風物詩を音楽で表現。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}